package com.hendri.exercise.testproject.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hendri.exercise.testproject.database.DtbTodo;

import com.hendri.exercise.testproject.database.DtbTodoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dtbTodoDaoConfig;

    private final DtbTodoDao dtbTodoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dtbTodoDaoConfig = daoConfigMap.get(DtbTodoDao.class).clone();
        dtbTodoDaoConfig.initIdentityScope(type);

        dtbTodoDao = new DtbTodoDao(dtbTodoDaoConfig, this);

        registerDao(DtbTodo.class, dtbTodoDao);
    }
    
    public void clear() {
        dtbTodoDaoConfig.getIdentityScope().clear();
    }

    public DtbTodoDao getDtbTodoDao() {
        return dtbTodoDao;
    }

}
